-- Run this in the Neon SQL editor or with psql connected to your Neon database.
-- Neon is PostgreSQL-compatible; use a JDBC URL like:
-- jdbc:postgresql://<host>/<database>?sslmode=require

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  current_session_token VARCHAR(255),
  device_model VARCHAR(255),
  device_os_version VARCHAR(255),
  email VARCHAR(255),
  google_id VARCHAR(255),
  kingschat_id VARCHAR(255),
  login_identifier VARCHAR(255),
  mac_address VARCHAR(255),
  name VARCHAR(255),
  otp_expiry TIMESTAMP(6),
  password VARCHAR(255),
  phone VARCHAR(255),
  platform VARCHAR(255),
  registered_at TIMESTAMP(6),
  reset_otp VARCHAR(255),
  reset_token VARCHAR(255),
  role VARCHAR(255),
  token_expiry TIMESTAMP(6),
  CONSTRAINT uk_users_email UNIQUE (email),
  CONSTRAINT uk_users_phone UNIQUE (phone),
  CONSTRAINT uk_users_mac_address UNIQUE (mac_address),
  CONSTRAINT uk_users_login_identifier UNIQUE (login_identifier)
);

CREATE INDEX IF NOT EXISTS idx_users_google_id ON users (google_id);
CREATE INDEX IF NOT EXISTS idx_users_kingschat_id ON users (kingschat_id);

CREATE TABLE IF NOT EXISTS fellowships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  leader_name VARCHAR(255),
  phone_number VARCHAR(255),
  location VARCHAR(255),
  state VARCHAR(255),
  city VARCHAR(255),
  meeting_time VARCHAR(255),
  description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255),
  subtitle VARCHAR(255),
  icon VARCHAR(255),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS idx_announcements_active_order ON announcements (active, display_order);

CREATE TABLE IF NOT EXISTS songs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255),
  artist VARCHAR(255),
  category VARCHAR(255),
  icon VARCHAR(255),
  drive_id VARCHAR(255),
  video_drive_id VARCHAR(255),
  description TEXT,
  lyrics TEXT,
  teaching_notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_songs_category ON songs (category);

CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  count INTEGER NOT NULL,
  submission_time TIMESTAMP(6),
  user_name VARCHAR(255),
  user_email VARCHAR(255),
  user_id BIGINT NOT NULL,
  CONSTRAINT fk_attendance_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_attendance_user_id ON attendance (user_id);
CREATE INDEX IF NOT EXISTS idx_attendance_submission_time ON attendance (submission_time);

CREATE TABLE IF NOT EXISTS fellowship_join_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fellowship_id BIGINT NOT NULL,
  user_name VARCHAR(255),
  user_email VARCHAR(255),
  user_phone VARCHAR(255),
  user_address VARCHAR(255),
  message VARCHAR(255),
  shared_with_emails VARCHAR(255),
  status VARCHAR(255),
  email_sent BOOLEAN NOT NULL DEFAULT FALSE,
  request_date TIMESTAMP(6),
  CONSTRAINT fk_join_requests_fellowship FOREIGN KEY (fellowship_id) REFERENCES fellowships (id)
);

CREATE INDEX IF NOT EXISTS idx_join_requests_fellowship_id ON fellowship_join_requests (fellowship_id);
CREATE INDEX IF NOT EXISTS idx_join_requests_status ON fellowship_join_requests (status);

CREATE TABLE IF NOT EXISTS foundation_enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255),
  phone VARCHAR(255),
  status VARCHAR(255),
  email_sent BOOLEAN NOT NULL DEFAULT FALSE,
  shared_with_emails VARCHAR(255),
  request_date TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS idx_foundation_enrollments_status ON foundation_enrollments (status);
CREATE INDEX IF NOT EXISTS idx_foundation_enrollments_email ON foundation_enrollments (email);
