spring.application.name=ce-pune-website

# =========================
# NEON POSTGRESQL DATABASE
# =========================

#spring.datasource.url=jdbc:postgresql://ep-late-haze-aznqti0e.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&currentSchema=cepune_db
#spring.datasource.username=neondb_owner
#spring.datasource.password=NewCePunePass2026!
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://ep-late-haze-aznqti0e.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&currentSchema=cepune_db}
spring.datasource.username=${DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${DATASOURCE_PASSWORD:NewCePunePass2026!}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.properties.hibernate.default_schema=cepune_db
spring.jpa.show-sql=true

# Hikari connection pool
spring.datasource.hikari.maximum-pool-size=${DB_MAX_POOL_SIZE:1}
spring.datasource.hikari.minimum-idle=${DB_MIN_IDLE:1}
spring.datasource.hikari.connection-timeout=${DB_CONNECTION_TIMEOUT_MS:30000}
spring.datasource.hikari.idle-timeout=${DB_IDLE_TIMEOUT_MS:600000}
spring.datasource.hikari.max-lifetime=${DB_MAX_LIFETIME_MS:1800000}

# =========================
# SERVER
# =========================

server.port=${PORT:8080}
server.address=0.0.0.0

# =========================
# FRONTEND
# =========================

frontend.url=https://ceindiazone2.in

# =========================
# MAIL CONFIGURATION
# =========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:cepune01@gmail.com}
spring.mail.password=gwbxlauwpjhxgmwa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =========================
# TWILIO
# =========================

twilio.account.sid=${TWILIO_ACCOUNT_SID:}
twilio.auth.token=${TWILIO_AUTH_TOKEN:}
twilio.phone.number=${TWILIO_PHONE_NUMBER:}

# =========================
# YOUTUBE
# =========================

youtube.api.key=UCSRZPEoL1Xa-33DCv-IHyAg
youtube.channel.id=${YOUTUBE_CHANNEL_ID:UCSRZPEoL1Xa-33DCv-IHyAg}



# =========================
# KINGSCHAT
# =========================

# --- KINGSCHAT CONFIGURATION ---
kingschat.client.id=b061ee24-5b7d-4126-b82b-a70fc29c23e1
kingschat.client.secret=r+/XXOTHTlTtn2RbUwcclasYNw7mPBUvZgBZ1EclkwA=
